#ifndef BOARD_LEDCONTROLLER_DEFAULT_CONFIG_H
#define BOARD_LEDCONTROLLER_DEFAULT_CONFIG_H

/**
 * Do NOT edit this file!
 *
 * This is the default LedController config file.
 * You may provide your own implementation at project level.
 *
 * For this:
 * - Copy/paste this file into a folder named 'config' in
 *   you projects include/source directory
 * - In this file rename the define BOARD_LEDCONTROLLER_DEFAULT_CONFIG_H to
 *   BOARD_LEDCONTROLLER_CONFIG_H and adjust the content of it to your needs
 */

#define LEDCONTROLLER_TRACE_ENABLE      1

#endif // BOARD_LEDCONTROLLER_DEFAULT_CONFIG_H
