#ifndef HAL_UART_DEFAULT_CONFIG_H
#define HAL_UART_DEFAULT_CONFIG_H

/**
 * Do NOT edit this file!
 * 
 * This is the default UART config file.
 * You may provide your own implementation at project level.
 * 
 * For this:
 * - Copy/paste this file into a folder named 'config' in
 *   you projects include/source directory
 * - In this file rename the define HAL_UART_DEFAULT_CONFIG_H to
 *   HAL_UART_CONFIG_H and adjust the content of it to your needs
 */

#include "mcu/mcu.h"

#endif // HAL_UART_DEFAULT_CONFIG_H
